### ISSUE TITLE
Heal using Backspace

### ISSUE THREAD

**Issue by apoapostolov** [tonifisler/foundry-token-health#7]
Press Enter to deal damage has a very simple and logical counter-button, Backspace for the heal by entered value.

**Comment by tonifisler** [comment]
Good idea, I'll see how I can implement that!

**Comment by tonifisler** [comment]
I added a new setting for an alternate healing key. 

I don't think Backspace is the ideal solution though since it's used to delete a token on the board. I chose to set the default alt key to <kbd>Shift</kbd>+<kbd>Enter</kbd>. You will be able to change to another if you want to!

Update is coming =)
